name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install Allure Playwright
      run: npm install -D allure-playwright allure-commandline
    
    - name: Install Playwright
      run: npx playwright install chromium firefox

    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true
    
    - name: Generate Allure Report
      run: npx allure generate ./allure-results --clean -o ./allure-report
    
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
